<article>
	<header class="hidden-xs">
		<h3 style="margin-top: 0px;">Einstein@Home</h3>
	</header>
	<hr class="hidden-xs"/>
	<p style="margin-top: 10px;">Einstein@Home is a World Year of Physics 2005 and an International Year of Astronomy 2009 project. It is supported by the American Physical Society (APS), the US National Science Foundation (NSF), the Max Planck Society (MPG), and a number of international organizations.</p>
	<p>Einstein@Home searches through weak astrophysical signal data from the LIGO detectors, the Arecibo radio telescope, and the Fermi gamma-ray satellite, for evidence of continuous gravitational-wave sources, which are expected from objects such as rapidly spinning non-axisymmetric neutron stars. The project is hosted by the University of Wisconsin–Milwaukee and the Max Planck Institute for Gravitational Physics (Albert Einstein Institute, Hannover, Germany).</p>
	<p>The project was officially launched on 19 February 2005 as part of the American Physical Society's contribution to the World Year of Physics 2005 event.</p>
	<p>12 August 12 2010 saw the first discovery by Einstein@Home of a previously undetected radio pulsar J2007+2722, found in data from the Arecibo Observatory. This was the first of dozens of further radio pulsars discovered by the project's volunteers.</p>
	<p>The Einstein@Home project was created to perform all-sky searches for previously unknown continuous gravitational-wave (CW) sources using data from the LIGO detector instruments. The primary class of target CW sources is rapidly rotating neutron stars (including pulsars) which are expected to emit gravitational waves due to a deviation from axisymmetry. Besides validating Einstein's theory of General Relativity, direct detection of gravitational waves would also constitute an important new astronomical tool. As most neutron stars are electromagnetically invisible, gravitational-wave observations might allow completely new populations of neutron stars to be revealed. A CW detection could potentially be extremely helpful in neutron-star astrophysics and would eventually provide unique insights into the nature of matter at high densities.</p>
	<p>The long-term goal is to make the first direct detections of gravitational-wave emission from spinning neutron stars. Gravitational waves were predicted by Albert Einstein a century ago, and were directly seen for the first time on 14 September 2015. This observation of gravitational waves from a pair of merging black holes opens up a new window on the universe, and ushers in a new era in astronomy.</p>
	<p>This first direct measurement was made soon after the advanced LIGO instruments came online after an extensive five-year upgrade. These advanced detectors took data between September 2015 and January 2016 and can already "see" three to six times as far as initial LIGO, depending upon the source type. Over the next two years this will increase to a factor of ten or more, increasing the number of potentially-visible gravitational-wave sources by a factor of a thousand!</p>
	<p>Since March 2009, part of the Einstein@Home computing power has also been used to analyse data taken by the PALFA Consortium at the Arecibo Observatory in Puerto Rico. This search effort is designed to find radio pulsars in tight binary systems.</p>
	<p>Einstein@Home has carried out a number of analysis runs using data from the LIGO instruments. Since its first search run in 2005, the quality of the LIGO data has consistently improved from enhanced detector instrument performance. Einstein@Home search algorithms have kept pace with the LIGO's evolution in technology, achieving an increasing search sensitivity.</p>
	<p>Einstein@Home's first analysis used data from the "third science run" (S3) of LIGO. Processing of the S3 data set was conducted between 22 February 2005 and 2 August 2005. This analysis employed 60 segments from the LIGO Hanford 4-km detector, totalling ten hours of data each. Each 10-hour segment was analysed for CW signals by the volunteers' computers using a matched-filtering technique. When all matched-filtering results were returned, the results from different segments were then combined in a "post-processing step" on Einstein@Home servers via a coincidence scheme to further enhance search sensitivity. Results were published on the Einstein@Home webpages.</p>
	<p>Work on the S4 data set (LIGO's fourth science run) was started via interlacing with the S3 calculations, and finished in July 2006. This analysis used 10 segments of 30 hours each from the LIGO Hanford 4-km detector and 7 segments of 30 hours each from the LIGO Livingston 4-km detector. Besides the S4 data being more sensitive, a more sensitive coincidence combination scheme was also applied in the post-processing. The results of this search have led to the first scientific publication of Einstein@Home in Physical Review D.</p>
	<p>Einstein@home gained considerable attention in the international distributed computing community when an optimised application for the S4 data set analysis was developed and released in March 2006 by project volunteer Akos Fekete, a Hungarian programmer. Fekete improved the official S4 application and introduced SSE, 3DNow! and SSE3 optimisations into the code improving performance by up to 800%. Fekete was recognized for his efforts and was afterward officially involved with the Einstein@home team in the development of the new S5 application. The app created a large surge in the project's total performance and productivity, as measured by floating point speed (or FLOPS), which over time has increased by approximately 50% compared to non-optimised S4 applications.</p>
	<p>The first Einstein@Home analysis of the early LIGO S5 data set, where the instruments initially reached their design sensitivity, began on 15 June 2006. This search used 22 segments of 30 hours each from the LIGO Hanford 4-km detector and 6 segments of 30 hours from the LIGO Livingston 4-km detector. This analysis run (code name "S5R1"), employing the search methodology as Einstein@Home, was very similar to the previous S4 analysis. However, the search results were more sensitive due to the use of more data of better quality compared to S4. Over large parts of the search parameter space, these results, which also appeared in Physical Review D, are the most exhaustive published to date.</p>
	<p>The second Einstein@Home search of LIGO S5 data (code name "S5R3") constituted a further major improvement in terms of search sensitivity. As opposed to previous searches, the ensuing results were already combined on the volunteers' computers via a Hough transform technique. This method matched-filtered results from 84 data segments of 25 hours each, parameters from which came from both 4-km LIGO Hanford and Livingston instruments. The results of this search are currently undergoing further examination.</p>
	<p>On 26 November 2009, a CUDA-optimized application for the Arecibo Binary Pulsar Search was first detailed on official Einstein@home webpages. This application uses both a regular CPU and an NVIDIA GPU to perform analyses faster (in some cases up to 50% faster).</p>
	<p>On 07 May 2010, a new Einstein@Home search (code name "S5GC1"), which uses a significantly improved search method, launched. This program analysed 205 data segments of 25 hours each, using data from both 4-km LIGO Hanford and Livingston instruments. It employed a technique which exploited global parameter-space correlations to efficiently combine the matched-filtering results from the different segments.</p>
	<p>12 August 2010: the Einstein@Home project announced the discovery of a new disrupted binary pulsar, PSR J2007+2722; it may be the fastest-spinning such pulsar discovered to date.</p>
	<p>01 March 1 2011: the project announced their second discovery: a binary pulsar system PSR J1952+2630.</p>
	<p>By 15 May 2012, Einstein@Home volunteers had discovered three new radio pulsars (J1901+0510, J1858+0319, and J1857+0259) in Arecibo PALFA data, and a new application for ATI/AMD graphic cards had been released. Using OpenCL, the new application was 10 times faster than running on a typical CPU. The application is currently available for Windows and Linux computers with Radeon HD 5000 or better graphics cards.</p>
	<p>In March 2016, Einstein@home began a search of the advanced-generation LIGO O1 data. The search focuses on signals with frequencies between 20 Hz and 100 Hz. The search includes two components, one for standard ever-lasting continuous gravitational waves and another for continuous signals lasting only some days.</p>
	<p>In its analysis of radio data from the Arecibo Observatory, Einstein@Home has re-detected 134 different known radio pulsars that include 8 millisecond pulsars.</p>
	<img src="http://boincstats.com/signature/5/user/2736906/project/sig.png" alt="Einstein Stats"/>
</article>